import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
const montserrat = Montserrat({ subsets: ['latin'] })
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-black">
      <ChakraProvider>
        <body
          style={{ backgroundColor: '#0000', color: '#ffffff' }}
          className={montserrat.className}
        >
          {children}
        </body>
      </ChakraProvider>
    </html>
  )
}
